# Example Snyk script for GitLab CI/CD Pipeline with Node.js project using Jira Snyk Sync


stages:
  - test
  - test_results


dependency_scanning:
  image: node:latest
  stage: test
  script:
    # Install npm, snyk, and snyk-to-html
    - npm install -g npm@latest
    - npm install -g snyk
    - npm install snyk-to-html -g
    # Run snyk help, snyk auth, snyk monitor, snyk test to break build and out report
    - snyk --help
    - snyk auth $SNYK_TOKEN
    - snyk monitor --project-name=goof-gitlab
    - snyk test --json | snyk-to-html -o snyk_results.html
 
  # Save report to artifacts
  artifacts:
    when: always
    paths: 
      - snyk_results.html

jira_tickets_for_new_snyk_vulns:
  image: ubuntu:latest
  stage: test_results
  variables:
    SNYK_TOKEN: $SNYK_TOKEN
    orgID: <OrgID>
    jiraProjectKey: <jiraProjectKey>
    # projectID: <projectID>
    # severity: <severity>
  script:
    # do i need to use sudo here? I don't think so because I'm using a docker image but I'm not sure
    curl -LO 'https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/releases/download/1.25.0/snyk-jira-sync-linux'
    chmod +x snyk-jira-sync-linux
    ls -l
    ./snyk-jira-sync-linux --orgID $orgID --token $SNYK_TOKEN --jiraProjectKey $jiraProjectKey --severity $severity --projectID $projectID --debug True
